unit-tests:
  name: Unit Tests
  runs-on: ubuntu-latest
  needs: stylelint # if you want to run after stylelint job is successful

  steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Node.js dependencies
      run: npm install

    - name: Run Jest Tests
      run: npx jest

e2e-tests:
  name: E2E Tests
  runs-on: ubuntu-latest
  needs: unit-tests # if you want to run after unit tests job is successful

  steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: npm install

    - name: Run Cypress Tests
      run: npx cypress run
